---
abstract: 'HTML form Validation, easy and flexibly'
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validator-Custom
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/yuki-kimoto/Validator-Custom.git
version: 0.23
