---
name: Validator-Custom
version: 0.1210
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Validates user input easily
license: perl
resources:
  license: ~
requires:
  Object::Simple: 3.0302
build_requires:
  Test::More: 0
provides:
  Validator::Custom:
    file: lib/Validator/Custom.pm
    version: 0.1210
  Validator::Custom::Basic::Constraints:
    file: lib/Validator/Custom/Basic/Constraints.pm
  Validator::Custom::Result:
    file: lib/Validator/Custom/Result.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
