--- #YAML:1.0
name:               Validator-Custom
version:            0.1406
abstract:           Validates user input easily
author:
    - Yuki Kimoto <kimoto.yuki@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
